apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: srvthreds

resources:
- ../base
- rabbitmq.yaml

images:
- name: srvthreds
  newTag: dev

patches:
- path: configmap-minikube.yaml

labels:
- pairs:
    environment: development
    version: dev