apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- srvthreds-bootstrap.yaml
- srvthreds-engine.yaml
- srvthreds-session-agent.yaml
- srvthreds-persistence-agent.yaml
