apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvthreds-engine
  namespace: srvthreds
  labels:
    app: srvthreds-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvthreds-engine
  template:
    metadata:
      labels:
        app: srvthreds-engine
    spec:
      containers:
        - name: srvthreds-engine
          image: srvthreds:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
              name: http
          envFrom:
            - configMapRef:
                name: srvthreds-config
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 500m
          command:
            - node
          args:
            - dist-server/src/ts/index.js
            - '-d'
---
apiVersion: v1
kind: Service
metadata:
  name: srvthreds-engine-service
  namespace: srvthreds
  labels:
    app: srvthreds-engine
spec:
  type: ClusterIP
  selector:
    app: srvthreds-engine
  ports:
    - name: http
      port: 8082
      targetPort: 8082
