apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvthreds-engine
  namespace: srvthreds
spec:
  template:
    spec:
      containers:
      - name: srvthreds-engine
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvthreds-session-agent
  namespace: srvthreds
spec:
  template:
    spec:
      containers:
      - name: srvthreds-session-agent
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvthreds-persistence-agent
  namespace: srvthreds
spec:
  template:
    spec:
      containers:
      - name: srvthreds-persistence-agent
        imagePullPolicy: Always
---
apiVersion: batch/v1
kind: Job
metadata:
  name: srvthreds-bootstrap
  namespace: srvthreds
spec:
  template:
    spec:
      containers:
      - name: bootstrap
        imagePullPolicy: Always
