apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvthreds-session-agent
  namespace: srvthreds
  labels:
    app: srvthreds-session-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvthreds-session-agent
  template:
    metadata:
      labels:
        app: srvthreds-session-agent
    spec:
      containers:
        - name: srvthreds-session-agent
          image: srvthreds:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3001
              name: websocket
          envFrom:
            - configMapRef:
                name: srvthreds-config
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 300m
          command:
            - node
          args:
            - dist-server/agent/agent.js
            - '-c'
            - session_agent
            - '-i'
            - org.wt.session1
            - '-d'
---
apiVersion: v1
kind: Service
metadata:
  name: srvthreds-session-agent-service
  namespace: srvthreds
  labels:
    app: srvthreds-session-agent
spec:
  type: ClusterIP
  selector:
    app: srvthreds-session-agent
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: websocket
      port: 3001
      targetPort: 3001
