apiVersion: v1
kind: ConfigMap
metadata:
  name: srvthreds-config
  namespace: srvthreds
data:
  NODE_ENV: development
  MONGO_HOST: host.minikube.internal:27017
  MONGO_DIRECT_CONNECTION: "true"
  REDIS_HOST: host.minikube.internal:6379
  RABBITMQ_HOST: rabbitmq:5672
  LOG_LEVEL: DEBUG