apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
# Infrastructure services
- mongo.yaml
- mongo-repl-1.yaml
- redis.yaml
- rabbitmq.yaml
# Application services
- srvthreds-bootstrap-job.yaml
- srvthreds-engine.yaml
- srvthreds-session-agent.yaml
- srvthreds-persistence-agent.yaml
