apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-managed-services.yaml
  - srvthreds-engine.yaml
  - srvthreds-session-agent.yaml
  - srvthreds-persistence-agent.yaml
  - srvthreds-bootstrap-job.yaml
  - namespace.yaml
