apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: srvthreds

resources:
- ../../base
- rabbitmq.yaml

images:
- name: srvthreds
  newName: srvthreds/app
  newTag: latest

patches:
- path: configmap-minikube.yaml
- path: srvthreds-bootstrap.yaml

labels:
- pairs:
    environment: development
    version: dev